version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # ระบุ path ของไดเรกทอรีที่มีไฟล์ package.json
    schedule:
      interval: "monthly" # ตั้งให้เช็คการอัปเดต dependencies ทุกเดือน
