name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: lefisius/dockerbuild

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Create New Branch with Commit Hash
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name Lefisius
          git config user.email lephiafuri@gmail.com
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          NEW_BRANCH_NAME="log-$(echo "$COMMIT_MESSAGE" | tr '[:upper:]' '[:lower:]' | tr '[:space:]' '-' | tr '[:punct:]' '-')"
          git checkout -b $NEW_BRANCH_NAME
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git $NEW_BRANCH_NAME

  zap_scan:
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Application
        run: |
          npm install --legacy-peer-deps
          npm run start &
          sleep 60

      - name: Run ZAP in Daemon Mode
        run: |
          docker run --rm -d -p 8080:8080 lefisius/dockerbuild:main zap.sh -daemon -host 0.0.0.0 -port 8080

      - name: Run ZAP Spider and Active Scan using API
        run: |
          # ทำการ spider ที่ http://localhost:4200
          curl "http://localhost:8080/JSON/spider/action/scan/?url=http://localhost:4200&maxChildren=10"
          sleep 30  # รอให้ spider เสร็จสิ้น
          # ทำการ active scan ที่ http://localhost:4200
          curl "http://localhost:8080/JSON/ascan/action/scan/?url=http://localhost:4200"

      - name: Save ZAP Report
        run: |
          # ดึงรายงานจาก ZAP และบันทึกเป็นไฟล์ HTML
          curl "http://localhost:8080/OTHER/core/other/htmlreport/" -o ./output/zap_report.html

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ./output/zap_report.html