name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Application
        run: |
          npm install --legacy-peer-deps
          npm run start &
          sleep 60

      - name: Create output directory
        run: |
          mkdir -p output
          chmod 777 output

      - name: Run ZAP daemon mode
        run: |
          docker run --rm -d -v ${{ github.workspace }}/output:/output -p 8081:8081 lefisius/dockerbuild:main /zap/ZAP_WEEKLY_D-2024-09-17/zap.sh -daemon -config api.key=${{ secrets.ZAP_API_KEY }} -port 8081
          sleep 30

      - name: Run ZAP Spider via API
        run: |
          curl "http://localhost:8081/JSON/spider/action/scan/?apikey=${{ secrets.ZAP_API_KEY }}&url=http://localhost:4200"
          sleep 60  # Wait for spider to finish

      - name: Run ZAP Active Scan via API
        run: |
          curl "http://localhost:8081/JSON/ascan/action/scan/?apikey=${{ secrets.ZAP_API_KEY }}&url=http://localhost:4200"
          sleep 120  # Wait for active scan to finish

      - name: Save ZAP report
        run: |
          curl "http://localhost:8081/OTHER/core/other/htmlreport/?apikey=${{ secrets.ZAP_API_KEY }}" -o output/zap_report.html

      - name: Check output directory
        run: ls -l output

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ./output/zap_report.html
