name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create output directory
        run: |
          mkdir -p output
          chmod 777 output

      - name: Run ZAP scan
        run: |
            docker run --rm -v ${{ github.workspace }}/output:/output lefisius/dockerbuild:main zap.sh -cmd -quickurl http://localhost:4200 -quickout /output/zap_report.html

      - name: Check output directory
        run: ls -l output

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ./output/zap_report.html
