name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: lefisius/dockerbuild

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  zap_scan:
    name: Run ZAP Scan
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Run ZAP scan
        run: |
          docker run --rm -v ${{ github.workspace }}:/zap lefisius/dockerbuild:main java -jar /zap/ZAP_D-2024-09-17/zap-D-2024-09-17.jar -cmd -quickurl http://localhost:8081/ -quickout /zap/zap_report.html
        shell: bash
        env:
          ZAP_API_KEY: ${{ secrets.ZAP_API_KEY }}
