name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Application
        run: |
          npm install --legacy-peer-deps
          npm run start &
          sleep 60

      - name: Create output directory
        run: |
          mkdir -p output
          chmod 777 output

      - name: Run ZAP in daemon mode
        run: |
            docker run -d --name zap -p 8080:8080 -v ${{ github.workspace }}/output:/output lefisius/dockerbuild:main
            sleep 30  # wait for ZAP to start

      - name: Run Spider
        run: |
            curl "http://localhost:8080/JSON/spider/action/scan/?url=http://localhost:4200&maxDepth=1&apikey=your_api_key"
            sleep 30  # wait for spider to finish

      - name: Active Scan
        run: |
            curl "http://localhost:8080/JSON/ascan/action/scan/?url=http://localhost:4200&apikey=your_api_key"
            sleep 30  # wait for active scan to finish

      - name: Generate Report
        run: |
            curl "http://localhost:8080/OTHER/htmlreport/generate/?apikey=your_api_key" -o /output/zap_report.html

      - name: Stop ZAP
        run: |
            docker stop zap
            docker rm zap

      - name: Check output directory
        run: ls -l output

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ./output/zap_report.html
