name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Application
        run: |
          npm install --legacy-peer-deps
          npm run start &
          sleep 60

      - name: Run ZAP in Daemon Mode
        run: |
          wget https://github.com/zaproxy/zaproxy/releases/download/w2024-09-17/ZAP_WEEKLY_D-2024-09-17.zip
          unzip ZAP_WEEKLY_D-2024-09-17.zip -d /zap
          docker run --rm -d -p 8080:8080 -v /zap:/zap lefisius/dockerbuild:main zap.sh -daemon -host 0.0.0.0 -port 8080

      - name: Run ZAP Spider and Active Scan using API
        run: |
          curl "http://localhost:8080/JSON/spider/action/scan/?url=http://localhost:4200&maxChildren=10"
          sleep 30 
          curl "http://localhost:8080/JSON/ascan/action/scan/?url=http://localhost:4200"

      - name: Save ZAP Report
        run: |
          curl "http://localhost:8080/OTHER/core/other/htmlreport/" -o ./output/zap_report.html

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ./output/zap_report.html
