name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Start Application
        run: |
          npm install --legacy-peer-deps
          npm run start &
          sleep 60

      - name: Create output directory
        run: |
          mkdir -p output
          chmod 777 output

      - name: Run ZAP in daemon mode
        run: |
            docker run -d --name zap -p 8081:8081 -v ${{ github.workspace }}/output:/output lefisius/dockerbuild:main

      - name: Wait for ZAP to start
        run: |
          for i in {1..6}; do
            if curl -s "http://localhost:8081" > /dev/null; then
              echo "ZAP is up and running!"
              break
            fi
            echo "Waiting for ZAP to start..."
            sleep 10
          done

          if [ $? -ne 0 ]; then
            echo "ZAP failed to start. Checking logs..."
            docker logs zap || echo "No logs available"
            exit 1
          fi

      - name: Run Spider
        run: |
            curl "http://localhost:8081/JSON/spider/action/scan/?url=http://localhost:4200&maxDepth=1&apikey=${{ secrets.ZAP_API_KEY }}"
            sleep 30

      - name: Generate Report
        run: |
            curl "http://localhost:8081/OTHER/htmlreport/generate/?apikey=${{ secrets.ZAP_API_KEY }}" -o /output/zap_report.html

      - name: Stop ZAP
        run: |
            docker stop zap
            docker rm zap

      - name: Check output directory
        run: ls -l output

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: ./output/zap_report.html
