name: Run API, Web, and Playwright Tests

on:
  push:
    branches:
      - dorn-ci
  pull_request:
    branches:
      - dorn-ci
  workflow_dispatch:
    inputs:
      api_branch:
        description: 'API branch to checkout'
        required: true
        default: 'main'
      web_branch:
        description: 'Web branch to checkout'
        required: true
        default: 'dorn-ci'

jobs:
  determine-api-branch:
    runs-on: ubuntu-latest
    outputs:
      api_branch: ${{ steps.set_branch.outputs.branch }}
    steps:
      - name: Set API branch
        id: set_branch
        run: echo "::set-output name=branch::${{ github.event.inputs.api_branch || 'main' }}"

  trigger-api:
    runs-on: ubuntu-latest
    needs: determine-api-branch
    steps:
      - name: Trigger API workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: Theerapat-dev/PresidentDemo-API
          event-type: run-api
          client-payload: '{"branch": "${{ needs.determine-api-branch.outputs.api_branch }}"}'

  run-api:
    needs: trigger-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v3
        with:
          repository: Theerapat-dev/PresidentDemo-API
          ref: ${{ needs.determine-api-branch.outputs.api_branch }}
          token: ${{ secrets.GH_PAT }}
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Build and Run Spring Boot API
        run: |
          mvn clean install
          nohup mvn spring-boot:run > /dev/null 2>&1 &

  run-web-and-test:
    needs: run-api
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Web repository
        uses: actions/checkout@v3
        with:
          repository: Theerapat-dev/PresidentDemo-Web
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.inputs.web_branch || 'dorn-ci' }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set npm registry
        run: npm config set registry https://registry.npmjs.org/
      - name: Install dependencies
        run: npm install --force
      - name: Start the app
        run: |
          npm start &
          npx wait-on http://localhost:4200
        env:
          PORT: 4200
      - name: Install Playwright
        run: npx playwright install
      - name: Run Playwright tests
        id: run-tests
        run: |
