name: ZAP Baseline Scan

on: 
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start the application
      run: |
        npm install --legacy-peer-deps
        npm run build
        npm start &
        sleep 10 # รอให้แอปพลิเคชันเริ่มทำงาน

    - name: Run ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.3.0
      with:
        target: 'http://localhost:4200'
        cmd_options: '-r zap_report.html'

    - name: Upload ZAP report
      uses: actions/upload-artifact@v3
      with:
        name: zap-report
        path: zap_report.html
