name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.20.2'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Start Angular App
        run: |
          nohup ng serve --port 4200 --host 0.0.0.0 &
          sleep 60

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run OWASP ZAP
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:4200/'
          docker_name: 'lefisius/dockerbuild:main'
          issue_title: ZAP Full Scan Report
          fail_action: false