name: ZAP API Scan

on:
  push:
    branches:
      - main

jobs:
  ZAP_API_Scan:
    runs-on: ubuntu-latest
    name: ZAP_API_Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.8.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: "ghcr.io/zaproxy/zaproxy:stable"
          format: openapi
          target: "https://2146-61-7-146-25.ngrok-free.app/"
          cmd_options: "-a"

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v3
        with:
          name: ZAP_API_Scan
          path: |
            report_json.json
            report_md.md
            report_html.html
            