name: OWASP ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          token: ${{ secrets.GH_PAT }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://acec-61-7-146-25.ngrok-free.app/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -r zap_report.html'

      - name: Upload ZAP report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ZAP-Report
          path: zap_report.html