name: ZAP Baseline Scan

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://acec-61-7-146-25.ngrok-free.app/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'